name: Publish

on:
  push:
    tags:
      - "*.*.*"

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: npm build
        run: deno run -A ./scripts/build_npm.ts ${{ github.ref_name }}
      - name: npm publish
        run: cd dist/npm && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
